
## Setup

The setup files will get you ready for your analysis. It loads you libraries, needed tables, created directories for your outputs, and assigns some parameter values. 

Also assign max year of the analysis. 

```{r setup}

min.yr <-2018
max.yr <- 2025 #needs changes with each analysis
ID<- "YOURUSERID" #change this to your NatureCounts user ID. You will be prompted for a password. 

source("00-setup.R")

```

## Choose a collection 

```{r downloaddata, echo = TRUE, message = FALSE}

#select your collection manually for data cleaning. Here we select them all. 
collection <- c("ABOWLS", "QCOWLS", "ATOWLS", "BCOWLS", "ONOWLS", "SKOWLS", "MBOWLS")


```

## Data manipulations 

```{r data manip}

#define the target species
# sp.list<-c("Great Horned Owl", "Boreal Owl", "Northern Saw-whet Owl", "Barred Owl", "Great Grey Owl")

#All species in the NOS Collections with >200 records. Many of these will still not have enough data to model, but pulling out anyways. 
sp.list<-c("American Woodcock", "Barred Owl", "Boreal Owl", "Common Poorwill", "Eastern Screech-Owl", "Flammulated Owl", "Great Gray Owl", "Great Horned Owl", "Long-eared Owl", "Northern Saw-whet Owl", "Ruffed Grouse", "Western Screech-Owl", "Wilson's Snipe" )

#run cleaning scripts
source("i-datamanip.R") #Full count period, sum of target species per route

```

